-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/TextKitSubclasses/TextKitSubclasses/ColoringTextStorage.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-16 12:31:19 +0000



-- Objective C interface: @interface ColoringTextStorage
local ColoringTextStorage = objc.classInterface ("ColoringTextStorage") --[[ @inherits NSTextStorage]]
