-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/TextKitSubclasses/TextKitSubclasses/ColoringTextStorage.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:23:21 +0000



-- Objective C interface: @interface ColoringTextStorage
local ColoringTextStorage = objc.classInterface ("ColoringTextStorage") --[[ @inherits NSTextStorage]]
