-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/TextKitSubclasses/TextKitSubclasses/ViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-16 12:31:19 +0000



-- Objective C interface: @interface ViewController
local ViewController = objc.classInterface ("ViewController") --[[ @inherits UIViewController]]
