-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/TextKitSubclasses/TextKitSubclasses/ViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:23:21 +0000



-- Objective C interface: @interface ViewController
local ViewController = objc.classInterface ("ViewController") --[[ @inherits UIViewController]]
